2018-07-11 16:45:48,863 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:55]
2018-07-11 16:47:26,693 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:55]
2018-07-11 16:47:42,282 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:55]
2018-07-12 12:48:43,819 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:55]
2018-07-12 12:49:58,166 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:55]
2018-07-12 12:50:29,350 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:55]
2018-07-12 12:53:31,375 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NSwiZXhwIjoxNTMxMzU3MzU0LjgwNjA5NjN9.tZ-EIRHx3OCMqEpMdn8x-0j7FkRCKhcc_TGI7I95KnY [GET] [in c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\manoj\microblog\app\routes.py", line 177, in reset_password
    form = ResetPasswordForm()
NameError: name 'ResetPasswordForm' is not defined
2018-07-12 12:53:53,534 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NSwiZXhwIjoxNTMxMzU3MzU0LjgwNjA5NjN9.tZ-EIRHx3OCMqEpMdn8x-0j7FkRCKhcc_TGI7I95KnY [GET] [in c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\manoj\microblog\app\routes.py", line 177, in reset_password
    form = ResetPasswordForm()
NameError: name 'ResetPasswordForm' is not defined
2018-07-12 12:54:02,313 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NSwiZXhwIjoxNTMxMzU3MzU0LjgwNjA5NjN9.tZ-EIRHx3OCMqEpMdn8x-0j7FkRCKhcc_TGI7I95KnY [GET] [in c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\manoj\microblog\app\routes.py", line 177, in reset_password
    form = ResetPasswordForm()
NameError: name 'ResetPasswordForm' is not defined
2018-07-12 12:56:21,064 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:55]
2018-07-12 12:58:01,686 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:55]
2018-07-12 13:36:37,463 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:57]
2018-07-12 13:56:54,799 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:57]
2018-07-12 14:24:18,820 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:57]
2018-07-13 19:23:36,699 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:57]
2018-07-13 19:26:14,411 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:57]
2018-07-13 19:27:42,832 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:57]
2018-07-13 19:28:09,401 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:57]
2018-07-13 19:33:27,300 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:57]
2018-07-13 19:33:50,340 ERROR: Exception on /About_me [GET] [in c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: About_me() missing 1 required positional argument: 'token'
2018-07-13 19:34:14,955 ERROR: Exception on /About_me [GET] [in c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: About_me() missing 1 required positional argument: 'token'
2018-07-13 19:34:18,184 ERROR: Exception on /About_me [GET] [in c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: About_me() missing 1 required positional argument: 'token'
2018-07-13 19:34:19,372 ERROR: Exception on /About_me [GET] [in c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: About_me() missing 1 required positional argument: 'token'
